#cloud-config
hostname: cliente
users:
  - name: debian
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDuY/xX5VpFHKf9e4A0cz4eryNYhNnL5CksiOPLyQB7RFS/nfN2hIk7YcZXPtYEBIS1vdNPHScwEjBBOhxr50QTCw+5Pl75l+b889V7pZbCZxX4TkVBEv4b/LY8i5vfd70IByYQoad75u0W48VpZLwg/fGwtPh68vkTbMMPC8CKov0NrFw3qHQLKcI6L2XAgYZYxw5Mbs88z40mAlZO6vL+F/Ue7ID647fmth10oAKMBsxvIFBHJ/zoKE9iDBx3xXAqrKWDfsDOFxUt+9Nx9MRQgS3aSqilwdK6UzRXalo9oCs0ToLML8ylVJK2j8sTE2mfltSbby/0IRD5PG6NE2LW6mq5WmPRLyG529pL3sXFcVHUH7EsK1tN6ARGVWqO3I7mNjNhLhFvmadv79qwiVBK4jxeEVML+ya4h56HOh9FlAjHBIM0HrFYQya0/vKT/a8Z26ACir99Ib/lkoYUHIzsU6Rduh9s96lbvqin5Xcse3BQnNx1AFosOiWkx+KeHgE= diego@debian
chpasswd:
  expire: False
  users:
    - name: debian
      password: asdasd
      type: text
